### ISSUE TITLE
Do not store 'dynamic' data to database (name, url, icon, published, naviHide)

### ISSUE THREAD

**Issue by ronaldbarendse** [callumbwhyte/meganav#34]
Currently, all data used in the back office view is stored in the database, e.g.:

```json
{
  "id": 1000,
  "name": "Home",
  "url": "/en",
  "children": [],
  "icon": "icon-umb-content",
  "published": true,
  "naviHide": false,
  "title": "Return to home"
}
```

This causes stale data to be shown when the linked content name, URL, publish or visibility status is changed, besides just bloating the database. The property editor should create a `PropertyValueEditor` that removes unnecessary data (`ConvertEditorToDb()`) and enriches it with current values when rendering the back office view (`ConvertDbToEditor`). The URL should obviously only be removed when linking to content.

**Comment by callumbwhyte** [comment]
As of Meganav V2 & V3 this is no longer the case. Thanks for raising @ronaldbarendse!
