### ISSUE TITLE
MeganavEntityApiController throws exception when linked content is deleted

### ISSUE THREAD

**Issue by ronaldbarendse** [callumbwhyte/meganav#39]
The API controller currently throws the following exception when a non-existent entity ID is requested (deleted from recycle bin), e.g. `/umbraco/backoffice/Meganav/MeganavEntityApi/GetById?id=0`: `System.InvalidOperationException: A null value was returned where an instance of HttpResponseMessage was expected.`.

This could be fixed by changing the following line:
https://github.com/thecogworks/meganav/blob/efae678daa1c7898f67926234ac7419a69a494dc/src/Cogworks.Meganav/Web/Controllers/API/MeganavApiController.cs#L28
to
```c#
return this.NotFound();
```
The AngularJS controller could even be updated to report these items (like with unpublished items) or even automatically remove them...

**Comment by mzajkowski** [comment]
@ronaldbarendse great finding! Can you submit a PR with this change?

**Comment by callumbwhyte** [comment]
Closing as this controller is now gone in V2 / V3 of Meganav.
