### ISSUE TITLE
Usability when you have a large navigation

### ISSUE THREAD

**Issue by NikRimington** [callumbwhyte/meganav#40]
So, we are using this on a project and the number of menu items is 162, 
As you can imagine this is a bit of a pain when you want to add a new item in position 25 for example. 

You have to add it at the bottom and then slowly, tediously, move it up the tree.

So 2 thoughts

1) Ability to add items anywhere in the tree straight away.
2) Ability to collapse tree sections - when collapsed maybe an indicator shows how many children there are currently hidden (or a "summary block" appears saying how many sub nodes there are) 

Not quite sure how the usability/functionality of this would work exactly but I do feel it's an area that needs to addressed to massively improved the usability when building a "meganav" type structure.

**Comment by callumbwhyte** [comment]
Thanks @NikRimington! That's the biggest use case for Meganav I've heard of, congrats! 🥇

Totally agree the current implementation is not really geared up to handling large quantities of data.

Both of your ideas are things I have explored and I think should be done. This should probably be achieved by adding some additional controls on each item.

The UX of this proposal needs to be explored, which is a key focus for v2.0.0 of this package.

**Comment by NikRimington** [comment]
No worries :-) If you want to discuss UI/UX ideas just shout, happy to feed back ideas/thoughts. I love the package just have to run a custom build of it at the minute so looking forward to being able to use the main one again!

**Comment by callumbwhyte** [comment]
Cheers @NikRimington, I'll likely take you up on that!

**Comment by callumbwhyte** [comment]
Hey @NikRimington,

I think V2 / V3 goes some way to fixing this. It's now possible to expand / collapse the tree, at either an individual item level or for the whole tree.

In addition, you can now replace the UI that renders for a nav item with your own that might be better suited for editors - e.g. multiple dropdowns under a single item could be stacked horizontally and side scroll.

Cheers,
Callum
