### ISSUE TITLE
Idea - Pre-populate meganav based on current site structure

### ISSUE THREAD

**Issue by NikRimington** [callumbwhyte/meganav#46]
If adding MegaNav to an existing site. It would be really cool if you could have the option to run a process that pre-populates the property editor based on the existing site structure. This could save creating the nav from scratch.

It should be optional :-)

**Comment by callumbwhyte** [comment]
Hey @NikRimington 

I really like the idea! Any ideas where this "process" would live? I can't see it making sense in the content or datatype editor personally...

Cheers,
Callum

**Comment by NikRimington** [comment]
Honestly, this was where I wasn't sure. Part of me thought a dashboard, part of me thought an optional content app. But I couldn't get my head around the right scenario.

If it was a flag on the datatype editor "Pre-populate on first save" then the property data would need a hidden field on it that stored a true/false saying "first save" then that can be set during the save event when populating it.

**Comment by skttl** [comment]
Could be done with property actions once they get into Umbraco:
https://github.com/umbraco/Umbraco-CMS/pull/6823

**Comment by callumbwhyte** [comment]
Ohhh that is lovely! Ideal solution IMHO 😊Will mean it's restricted to v8 latest though
