### ISSUE TITLE
v8

### ISSUE THREAD

**Issue by kows** [callumbwhyte/meganav#47]
Any plans on this yet?
Perhaps even just strategy/approach explained so this could be up for grabs for anyone :)
Seperate branch/repo/backwards compat (multi project?) ..?

**Comment by mzajkowski** [comment]
Bumping it up as I'm also curious how we all can help to make it **DONE** (without duplicating possible work already being completed).

🤔

**Comment by kows** [comment]
News will come soon (sneak preview @buug)

**Comment by callumbwhyte** [comment]
As @kows says, confirmed! A new version *does* exist, but it's not public yet.

In fact it's a complete rewrite of the V7 version, and a new version for V8... Code isn't open for collaboration yet, but will be very very soon!

I have been running it in production for a little while but I will also need some guinea pigs to test on...

**Comment by markroffey** [comment]
Hey, was wondering if there's a pre-release package we could test and use?

Currently working on a project that would love to see some MegaNav love!

**Comment by loriRyanp** [comment]
Equally would love a version of this for Umbraco 8  - be great to get an update @callumbwhyte

**Comment by ruant** [comment]
Use this a lot on all the U7 projects I've done. Would LOVE to keep on using it in U8 projects.
Any news @callumbwhyte? What can the community help out with?

**Comment by stefankip** [comment]
It doesn't seem like this project is on @callumbwhyte his priorities list right now:
https://twitter.com/kipusoep/status/1260899016419704833

**Comment by callumbwhyte** [comment]
I appreciate everyone's excitement about Meganav for V8!

I'd like to give a FRIENDLY reminder that Meganav is a tool I created and maintain for free, in my own time. I do have other priorities and important things that require my attention, especially right now given the current global situation 😊

As mentioned in the previous comments, I do have a new version of Meganav for both V7 and V8 in the works. I haven't released it publicly as I'm still not 100% happy with it, but it's running in production on a number of my sites.

However, for those who have requested it I've always been happy to provide a preview of the V8 release. You can download it [here](https://github.com/callumbwhyte/meganav/releases/tag/v2.0.0).

This isn't officially a supported version, and the final change will definitely have breaking changes, but hopefully this is enough to get people moving until I release the final version.

Thanks everyone for your patience!

**Comment by stefankip** [comment]
I understand. The only thing I'm a bit annoyed by, is the fact that you stated "Will check and get back to you. Preparing it for release." and then there's radio silence.
So now I have to remove Meganav and migrate to something else, that's just a bit annoying, sorry.

**Comment by callumbwhyte** [comment]
I'm sorry you feel that way @stefankip.

As with all open source projects, these things rely on the generosity of the community. I haven't had an opportunity to look into it, for the reasons I mentioned.

You are of course welcome to choose another solution if this version of the package isn't what you need. Similarly, I provided you with the code so you are welcome to look into any issues you are experiencing.

**Comment by callumbwhyte** [comment]
v2 of Meganav is out for Umbraco 8, and v3 for Umbraco 9
