### ISSUE TITLE
Is there a demo available?

### ISSUE THREAD

**Issue by seanrockster** [callumbwhyte/meganav#52]
Hi

Is there a demo or something I can see before installing this package?

Thanks.

**Comment by callumbwhyte** [comment]
Hey @seanrockster,

Thanks for your interest in Meganav!

I did a demo of all of the features on UmbraCoffee a few weeks back: https://youtu.be/lu_SW2Nu1eM?t=1015

Let me know if you have any questions.

Cheers,
Callum

**Comment by seanrockster** [comment]
Ah, cool, looks awesome. Great work!
