### ISSUE TITLE
CSS syntax causes NUglify CSS to (incorrectly) break backoffice CSS bundles

### ISSUE THREAD

**Issue by eden-jh** [callumbwhyte/meganav#59]
## The issue

Meganav prevents the backoffice custom CSS (anything from a package, property editor, or loaded by a package.manifest) from loading correctly when Umbraco debug mode (Umbraco.Hosting.Debug) is turned off.

![Meganav property editor loaded with no style. The numbers of the ordered list are visible and icons and text are visible, but there are no recognizable UI components](https://user-images.githubusercontent.com/55098579/166060398-e76a9091-4f66-4e3d-9258-4d9b6b56a8db.png)

![Network panel showing a 500 error for umbraco-backoffice-css.css](https://user-images.githubusercontent.com/55098579/166060891-63ef0c9f-cb8a-4363-93a6-eeeb6dc60227.png)

### The cause

When Umbraco debug mode is on, custom CSS is loaded without any minification. When it's off, custom CSS is minified and bundled together into umbraco-backoffice-css.css. 

The syntax of the box-shadow at [line 30 of meganav.css](https://github.com/callumbwhyte/meganav/blob/25111e95c26495d37436b3430072692373ea722f/src/Our.Umbraco.Meganav/Web/UI/App_Plugins/Meganav/backoffice/meganav.css#L30) is (incorrectly) flagged as an error by Smidge/Nuglify during the bundling/minification process:

![An error level log in the Umbraco Log Viewer. The Message says 'An unhandled exception has occurred while executing the request.' The stack trace shown is in the issue text following this image ](https://user-images.githubusercontent.com/55098579/166017199-bb3b0b51-6e39-4025-baff-a787d9bcfe8c.png)

> System.InvalidOperationException: Expect comma, found '0',Expect comma, found '/'
> at Smidge.Nuglify.NuglifyCss.ProcessAsync(FileProcessContext fileProcessContext, PreProcessorDelegate next)
>    at Smidge.FileProcessors.PreProcessPipeline.ProcessNext(Queue`1 queue, FileProcessContext fileProcessContext)
>    at Smidge.FileProcessors.PreProcessPipeline.<>c__DisplayClass5_0.<<ProcessNext>b__0>d.MoveNext()
> --- End of stack trace from previous location ---

Debugging confirmed the issue is specifically the "/" character in the box-shadow:

https://github.com/callumbwhyte/meganav/blob/25111e95c26495d37436b3430072692373ea722f/src/Our.Umbraco.Meganav/Web/UI/App_Plugins/Meganav/backoffice/meganav.css#L30

The result of this is that **none of the CSS files that were intended to go in that bundle (including but not limited to Meganav) are loaded**.

## Proposed Solution
The syntax can be changed to `0 1px 2px rgba(0, 0, 0, .2)`, which it seems to not flag as an error when I tried it in a different CSS file.

**I recognize that the original syntax is valid and that the underlying issue is with NUglify** (and I definitely plan to make an issue there if it doesn't exist already.) But a CSS syntax tweak should work, and should be a faster solution, even if it's just a short-term one.

**Comment by callumbwhyte** [comment]
Hey @eden-jh!

As I see you've commented @mattwootton already fixed this in #57, which has now been merged.

Thanks for using Meganav!
