### ISSUE TITLE
Content resets after saving datatype

### ISSUE THREAD

**Issue by patrickdemooij9** [callumbwhyte/meganav#63]
The navigation items will forget of which type they are part of when you save the datatype.

Umbraco version: 8.18.4
Package version: 2.0.1

**How to reproduce**

1. Create a navigation datatype with some types and some setting models
2. Add some items and also some content to the settings models
3. Go back to the datatype and save it (no changes needed)
4. Go back to your navigation. You'll see that the settings tab is now gone.

**Comment by callumbwhyte** [comment]
Hey @patrickdemooij9,

Thanks for raising – this is certainly a weird one...

Can you clarify where that screenshot of the data object is taken from? Does this expand even deeper when saving the data type...?

Cheers,
Callum

**Comment by callumbwhyte** [comment]
@patrickdemooij9 I've managed to pin this one down. The legacy value migrator was running even though the data type wasn't being changed. This is fixed in https://github.com/callumbwhyte/meganav/commit/096dc85f3a31c7a53d6034d63dd7a6910ebacaf7 and will be released in v2.0.2 / v3.0.2

**Comment by patrickdemooij9** [comment]
@callumbwhyte Great to hear that you managed to find it!
