### ISSUE TITLE
Umbraco v10 compatibility?

### ISSUE THREAD

**Issue by JHUMikeSchnell** [callumbwhyte/meganav#67]
Are there any plans for upgrading this so it's compatible with v10 of Umbraco?  We are currently using this, but are looking at upgrading the base Umbraco, but when we did a test, we found it didn't seem to work for us.

If there is a separate patch to obtain v10 compatibility, that would work too.

Thank you

**Comment by dampee** [comment]
Hi @JHUMikeSchnell 
This is prepared by a community member in PR #66 
If you can not wait, you'll need to checkout that branch and add it to your project manually.

**Comment by afabri73** [comment]
Hi,
there are updates about Umbraco 10 compatibility?
This package is very util and I would prefer to install it instead of add it manually.

Thank you for the support
Adriano

**Comment by callumbwhyte** [comment]
Closing this as v4 now supports all versions of Umbraco 9+.

Thanks for using Meganav!
